InvoicePrinter.labels = {
  name: 'Facture',
  provider: 'Fournisseur',
  purchaser: 'Acheteur',
  tax_id: 'Identification number',
  tax_id2: 'Identification number',
  payment: 'Paiement',
  payment_by_transfer: 'Paiement via stripe',
  payment_in_cash: 'Payment in cash',
  account_number: 'STRIPE',
  swift: 'SWIFT',
  iban: 'IBAN',
  issue_date: 'Date de debut d\'abonnement',
  due_date: 'Date de fin d\'abonnement',
  item: 'Titre',
  variable: '',
  quantity: 'Type',
  unit: 'Periode',
  price_per_item: 'Formule',
  amount: 'Montant',
  tax: 'Tax',
  tax2: 'Tax 2',
  tax3: 'Tax 3',
  subtotal: 'Subtotal',
  total: 'Total'
}