development:
 secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
 facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
 facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
 
test:
 secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
 facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
 facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
 
production:
 secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
 facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
 facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>